# Generated by Django 4.2.3 on 2023-07-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='products_buyed',
        ),
        migrations.AddField(
            model_name='sale',
            name='products_buyed',
            field=models.ManyToManyField(to='ecommerce.product'),
        ),
    ]
